apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb-deployment
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-deployment
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "dev"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "devpass"
        - name: MONGO_INITDB_DATABASE
          value: "mongodb"
        volumeMounts:
        - name: mongodb-pv
          mountPath: /data/db
        ports:
        - containerPort: 27017
        resources: {}
      volumes:
      - name: mongodb-pv
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
status: {}
