version: "3"
services:
  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
    networks:
      - toktik-back-office
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpass
      - MYSQL_ROOT_PASSWORD=devpass
    volumes:
      - mariadata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - toktik-back-office
  toktik-frontend:
    image: toktik-frontend
    build: ./frontend
    networks:
      - toktik-user-facing
  toktik-backend:
    image: toktik-backend
    build: ./backend
    depends_on:
      - mariadb
      - redis
    environment:
      - MARIA_DB_NAME=mariadb
      - MARIA_DB_USERNAME=dev
      - MARIA_DB_PASSWORD=devpass
      - MARIA_DB_PORT=3306
      - MARIA_DB_IP=mariadb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - toktik-user-facing
      - toktik-back-office
    links:
      - redis
  toktik-proxy:
    image: nginx:1.21
    ports:
      - "7887:80"
    depends_on:
      - toktik-backend
      - toktik-frontend
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - toktik-user-facing
volumes:
    mariadata:
      driver: local
    cache:
      driver: local
networks:
  toktik-user-facing:
  toktik-back-office:
