apiVersion: v1
data:
  s3-key-secret: QU9CcDJEMUdoVWQwNnBMYTBpNjBXQ3lEMTBNNllURHg2bG84YzlzUw==
kind: Secret
metadata:
  creationTimestamp: "2023-10-19T03:04:42Z"
  name: s3-key-secret
  namespace: default
  resourceVersion: "988"
  uid: 64750f11-fd20-4115-867d-36bcc9591f1e
type: Opaque

---

apiVersion: v1
data:
  s3-key-id: QUtJQVRUVjczNzVESVJaSUpCTTQ=
kind: Secret
metadata:
  creationTimestamp: "2023-10-19T03:12:50Z"
  name: s3-key-id
  namespace: default
  resourceVersion: "1640"
  uid: d3edc6e0-5bb1-41df-99ea-4aaacef22672
type: Opaque
