apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb-deployment
status:
  loadBalancer: {}
