apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-msgbroker
  name: redis-msgbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-msgbroker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-msgbroker
    spec:
      containers:
      - image: redis:7.2.1
        name: redis
        volumeMounts:
        - name: redis-msgbroker-volume
          mountPath: /data
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
      volumes:
      - name: redis-msgbroker-volume
status: {}
