apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: toktik-frontend-deployment
  name: toktik-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: toktik-frontend-deployment
status:
  loadBalancer: {}
