apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: toktik-backend-deployment
  name: toktik-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toktik-backend-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toktik-backend-deployment
    spec:
      containers:
      - image: ghcr.io/iccs-alex/toktik/toktik-backend:latest
        imagePullPolicy: Always
        name: toktik-backend
        env:
        - name: MARIA_DB_NAME
          value: "mariadb"
        - name: MARIA_DB_USERNAME
          value: "dev"
        - name: MARIA_DB_PASSWORD
          value: "devpass"
        - name: MARIA_DB_PORT
          value: "3306"
        - name: MARIA_DB_HOST
          value: "mariadb-service"
        - name: REDIS_HOST
          value: "redis-msgbroker-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_DB_HOST
          value: "mongodb-service"
        - name: MONGO_DB_PORT
          value: "27017"
        - name: MONGO_DB_NAME
          value: "mongodb"
        - name: MONGO_DB_USERNAME
          value: "dev"
        - name: MONGO_DB_PASSWORD
          value: "devpass"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-key-id
              key: s3-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-key-secret
              key: s3-key-secret
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
        - name: ghcr-secret
status: {}
