apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: toktik-conversion-deployment
  name: toktik-conversion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toktik-conversion-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toktik-conversion-deployment
    spec:
      containers:
      - image: toktik-conversion:v1
        imagePullPolicy: Never
        name: toktik-conversion
        ports:
        - containerPort: 5000
        resources: {}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-key-id
              key: s3-key-id
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-key-secret
              key: s3-key-secret
status: {}
