apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: toktik-thumbnail-deployment
  name: toktik-thumbnail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toktik-thumbnail-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toktik-thumbnail-deployment
    spec:
      containers:
      - image: ghcr.io/iccs-alex/toktik/toktik-thumbnail:latest
        imagePullPolicy: Always
        name: toktik-thumbnail
        ports:
        - containerPort: 5002
        resources: {}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-key-id
              key: s3-key-id
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-key-secret
              key: s3-key-secret
      imagePullSecrets:
        - name: ghcr-secret
status: {}
