apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-msgbroker
  name: redis-msgbroker-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-msgbroker
status:
  loadBalancer: {}
