apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: toktik-processing-deployment
  name: toktik-processing-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: toktik-processing-deployment
status:
  loadBalancer: {}
