apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: toktik-socketio-deployment
  name: toktik-socketio-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: toktik-socketio-deployment
status:
  loadBalancer: {}
